# Luminite Block — Shader Block Properties
# Supports: Complementary Reimagined, Complementary Unbound, BSL Shaders

block.10001 = wots:luminite_block[lit=true]
block.10216 = wots:luminite_block[lit=true]
block.10100 = wots:luminite_block[lit=true]

emissive.suffix = _lit
